if (CMAKE_C_COMPILER MATCHES "aarch64" AND CMAKE_CXX_COMPILER MATCHES "aarch64"
        AND CMAKE_C_COMPILER MATCHES "linux" AND CMAKE_CXX_COMPILER MATCHES "linux")
    set(CMAKE_SYSTEM_NAME "Linux")
    set(CMAKE_SYSTEM_PROCESSOR "aarch64")
    set(BINARY_PREFIX "arm64")
endif ()

if (CMAKE_C_COMPILER MATCHES "x86_64" AND CMAKE_CXX_COMPILER MATCHES "x86_64"
        AND CMAKE_C_COMPILER MATCHES "linux" AND CMAKE_CXX_COMPILER MATCHES "linux")
    set(CMAKE_SYSTEM_NAME "Linux")
    set(CMAKE_SYSTEM_PROCESSOR "x64")
    set(BINARY_PREFIX "x64")
endif ()