#ifndef SEB_MODULEINFO_HPP
#define SEB_MODULEINFO_HPP

#define MODULE_SEB_VERSION_NAME "1.0"
#define MODULE_SEB_VERSION_CODE 1
#define MODULE_SEB_VERSION_DEFAULT_VERSION "3.10.1"

#define MODULE_SEB_REQUIRED_LXEB_VERSION 1

#endif //SEB_MODULEINFO_HPP